- project:
    templates:
      - dci-build-and-push-container-template
    check:
      jobs:
        - dci-build-and-push-container-job:
            vars:
              registry: quay.io
              tag: distributedci/dci-provisioner
              dockerfile_path: Containerfiles/Containerfile-provisioner
    gate:
      jobs:
        - dci-build-and-push-container-job:
            vars:
              registry: quay.io
              tag: distributedci/dci-provisioner
              dockerfile_path: Containerfiles/Containerfile-provisioner
