- project:
    templates:
      - dci-build-and-push-container-template
    
    # check pipelin (PR)
    # run the build job, but hijack it to run the push playbook too.
    check:
      jobs:
        - dci-build-container-job:
            vars:
              version: "git{{ zuul['commit_id'][:7] }}"
              quay_expiration: 2w
              registry: quay.io
              tag: distributedci/dci-provisioner
              dockerfile_path: Containerfiles/Containerfile-provisioner
            
            # point to the central config project for playbooks
            run:
              - name: playbooks/containers/build.yaml
                project: gitlab.com/softwarefactory-project/centosinfra-prod/dci-config
              - name: playbooks/containers/push.yaml
                project: gitlab.com/softwarefactory-project/centosinfra-prod/dci-config

    # gate pipeline (merge)
    # run both snapshot and production builds.
    gate:
      jobs:
        # snapshot job
        - dci-build-and-push-container-snapshot-job:
            vars:
              # explicitly listing variables to fix "Dockerfile not found"
              registry: quay.io
              tag: distributedci/dci-provisioner
              dockerfile_path: Containerfiles/Containerfile-provisioner

        # production job
        - dci-build-and-push-container-job:
            vars:
              # explicitly listing variables here as well
              registry: quay.io
              tag: distributedci/dci-provisioner
              dockerfile_path: Containerfiles/Containerfile-provisioner
