# ----------------------------------------------------------------------
# 1. Custom Job Definition
# We create a child of the snapshot job to inherit its playbooks.
# We override 'provides' to empty so Zuul lets it run in PRs.
# ----------------------------------------------------------------------
- job:
    name: dci-provisioner-pr-push
    parent: dci-build-and-push-container-snapshot-job
    provides: []
    vars:
      version: "git{{ zuul['commit_id'][:7] }}"
      quay_expiration: 2w
      # Explicitly define path variables for the inherited playbooks
      registry: quay.io
      tag: distributedci/dci-provisioner
      dockerfile_path: Containerfiles/Containerfile-provisioner

# ----------------------------------------------------------------------
# 2. Project Configuration
# ----------------------------------------------------------------------
- project:
    templates:
      - dci-build-and-push-container-template
    
    # Global variables for the Gate jobs
    vars: &common_vars
      registry: quay.io
      tag: distributedci/dci-provisioner
      dockerfile_path: Containerfiles/Containerfile-provisioner

    # CHECK Pipeline (PR Submission)
    check:
      jobs:
        - dci-provisioner-pr-push

    # GATE Pipeline (Merge to Main)
    gate:
      jobs:
        - dci-build-and-push-container-snapshot-job:
            vars: *common_vars
        - dci-build-and-push-container-job:
            vars: *common_vars
