- project:
    templates:
      - dci-build-and-push-container-template
    vars: &common_vars
      registry: quay.io
      tag: distributedci/dci-provisioner
      dockerfile_path: Containerfiles/Containerfile-provisioner
    check:
      jobs:
        - dci-build-and-push-container-job:
            vars: *common_vars
            secrets:
              - quay_registry_secrets
    gate:
      jobs:
        - dci-build-and-push-container-job:
            vars: *common_vars
            secrets:
              - quay_registry_secrets
        - dci-build-and-push-container-snapshot-job:
            vars: *common_vars
            secrets:
              - quay_registry_secrets
