- project:
    templates:
      - dci-build-and-push-container-template
    vars:
      registry: quay.io
      tag: distributedci/dci-provisioner
      dockerfile_path: Containerfiles/Containerfile-provisioner
