- name: Load provisioner credentials
  ansible.builtin.set_fact:
    provisioner_username: "{{ lookup('env', 'DCI_CLIENT_ID') }}"
    provisioner_password: "{{ lookup('env', 'DCI_API_SECRET') }}"
  no_log: true
  delegate_to: localhost

- name: Create Temp DIr
  tempfile:
    state: directory
  register: temp_dir
  delegate_to: localhost

- name: Destroy VM
  include_tasks: destroy_vm.yml
  args:
    apply:
      delegate_to: localhost

- name: Create VM
  include_tasks: provision_vm.yml
  args:
    apply:
      delegate_to: localhost

- name: Setup BMC
  include_tasks: vbmc.yml
  args:
    apply:
      delegate_to: localhost

- name: Add SUT
  include_tasks: add_sut.yml
  args:
    apply:
      delegate_to: localhost
